namespace AtlasPacker;

/// <summary>
/// Dimensions of one obfuscated sheet file, keyed by sheet name (e.g. <c>"uf_terrain"</c>) in
/// <see cref="AtlasDocument.Sheets"/>.
/// </summary>
/// <param name="Width">Sheet width in pixels - needed by the renderer's percentage-based
/// <c>background-size</c>/<c>background-position</c> math.</param>
/// <param name="Height">Sheet height in pixels.</param>
/// <param name="File">Obfuscated file name on disk / served id, e.g. <c>"0.bin"</c> - deliberately
/// not the vendor sheet's own name.</param>
sealed record SheetInfo(int Width, int Height, string File);

/// <summary>
/// One sprite's location, keyed by opaque sprite name (e.g. <c>"archer"</c>,
/// <c>"wall_dungeon_12"</c>) in <see cref="AtlasDocument.Sprites"/>. A static sprite has
/// <see cref="FrameCount"/> 1; an animated one (heroes/monsters today) has <see cref="FrameCount"/>
/// &gt; 1 with each subsequent frame offset by (<see cref="FrameStrideX"/>,
/// <see cref="FrameStrideY"/>) from (<see cref="X"/>, <see cref="Y"/>).
/// </summary>
sealed record SpriteEntry(
    string Sheet,
    int X,
    int Y,
    int W,
    int H,
    int FrameCount = 1,
    int FrameStrideX = 0,
    int FrameStrideY = 0
)
{
    public (int X, int Y) FrameOrigin(int frame)
    {
        if (frame < 0 || frame >= FrameCount)
        {
            throw new ArgumentOutOfRangeException(
                nameof(frame),
                frame,
                $"Frame index must be in [0,{FrameCount})."
            );
        }

        return (X + frame * FrameStrideX, Y + frame * FrameStrideY);
    }
}

/// <summary>
/// The Locator tool's output: where every sprite the game references lives across the obfuscated
/// vendor sheets. Not checked into source control - it's derived from licensed content and
/// regenerated by <c>tools/AtlasPacker</c> on a machine that owns the Oryx license, then deployed
/// alongside the obfuscated sheet files. Never served to the browser as-is; the renderer consumes
/// it server-side to generate plain CSS.
/// </summary>
sealed record AtlasDocument(
    Dictionary<string, SheetInfo> Sheets,
    Dictionary<string, SpriteEntry> Sprites
);
