namespace AtlasPacker;

/// <summary>
/// Dimensions of one obfuscated sheet file, keyed by sheet name in <see cref="AtlasDocument.Sheets"/>.
/// </summary>
/// <param name="Width">Sheet width in pixels - needed by the renderer's percentage-based
/// <c>background-size</c>/<c>background-position</c> math.</param>
/// <param name="Height">Sheet height in pixels.</param>
/// <param name="File">Opaque file name on disk / served id, e.g. <c>"0.bin"</c>.</param>
sealed record SheetInfo(int Width, int Height, string File);

/// <summary>
/// One sprite's location, keyed by sprite name in <see cref="AtlasDocument.Sprites"/>. A static
/// sprite has <see cref="FrameCount"/> 1; an animated one (heroes/monsters today) has
/// <see cref="FrameCount"/> &gt; 1 with each subsequent frame offset by (<see cref="FrameStrideX"/>,
/// <see cref="FrameStrideY"/>) from (<see cref="X"/>, <see cref="Y"/>).
/// </summary>
sealed record SpriteEntry(
    string Sheet,
    int X,
    int Y,
    int W,
    int H,
    int FrameCount = 1,
    int FrameStrideX = 0,
    int FrameStrideY = 0
)
{
    public (int X, int Y) FrameOrigin(int frame)
    {
        if (frame < 0 || frame >= FrameCount)
        {
            throw new ArgumentOutOfRangeException(
                nameof(frame),
                frame,
                $"Frame index must be in [0,{FrameCount})."
            );
        }

        return (X + frame * FrameStrideX, Y + frame * FrameStrideY);
    }
}

/// <summary>
/// The tool's output: where every sprite the game references lives across the obfuscated sheets.
/// Not checked into source control (derived from licensed content); regenerated by
/// <c>tools/AtlasPacker</c> and deployed alongside the sheet files. Consumed server-side to
/// generate plain CSS, never served to the browser as-is.
/// </summary>
sealed record AtlasDocument(
    Dictionary<string, SheetInfo> Sheets,
    Dictionary<string, SpriteEntry> Sprites
);
