# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Publishing App...'
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
- task: UniversalPackages@0
  inputs:
    command: 'download'
    downloadDirectory: '$(System.DefaultWorkingDirectory)/wwwroot/img'
    feedsToUse: 'internal'
    vstsFeed: 'b6ba11a2-e28f-428c-a804-91d09380482a'
    vstsFeedPackage: 'efb6cc57-1ece-4180-b2b6-b29d5681cd94'
    vstsPackageVersion: '0.0.1'
    verbosity: 'Debug'
- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build Artifacts...'