namespace BlazorRogue.Entities;

/// <summary>
/// What happens to a <see cref="GameObjects.Moveable"/> that is in (or tries to leave) a liquid
/// pool tile - see <see cref="LiquidType"/>.
/// </summary>
enum LiquidEffectKind
{
    /// <summary>Cosmetic only.</summary>
    None,

    /// <summary>Chance (<see cref="LiquidType.EffectMagnitude"/> %) to fail a move out of the tile.</summary>
    Slow,

    /// <summary><see cref="LiquidType.EffectMagnitude"/> damage each turn ended standing in it.</summary>
    Acid,

    /// <summary>Kills anything that enters it outright.</summary>
    Instakill,
}

/// <summary>
/// A kind of liquid pool (water/mud/acid/lava), parsed from <c>Data/liquidsets.json</c>. The four
/// animation frames live at <c>wwwroot/img/uf_terrain/{SpriteName}_1..{FrameCount}.png</c>; the CSS
/// keyframes for them are generated by <see cref="Rendering.AnimationCssGenerator"/>. Carried on
/// <see cref="World.Tile.Liquid"/>; the tile itself keeps a plain black substrate tile-set under the
/// animated surface decoration.
/// </summary>
sealed class LiquidType(
    string id,
    string name,
    string spriteName,
    int frameCount,
    double animationDurationSeconds,
    int lipIndex,
    string asciiColor,
    LiquidEffectKind effectKind,
    int effectMagnitude
)
{
    /// <summary>The ASCII glyph every liquid renders as (coloured per <see cref="AsciiColor"/>).</summary>
    public const string AsciiCharacter = "~";

    public string Id { get; } = id;

    /// <summary>Lower-case display noun used in messages ("water", "mud", "acid", "lava").</summary>
    public string Name { get; } = name;

    /// <summary>Image filename stem, e.g. <c>water_blue</c> for <c>water_blue_1.png</c>.</summary>
    public string SpriteName { get; } = spriteName;

    public int FrameCount { get; } = frameCount;
    public double AnimationDurationSeconds { get; } = animationDurationSeconds;

    /// <summary><c>water_lip_{LipIndex}</c> - the shadow drawn on the northern shore edge.</summary>
    public int LipIndex { get; } = lipIndex;

    public string AsciiColor { get; } = asciiColor;

    public LiquidEffectKind EffectKind { get; } = effectKind;
    public int EffectMagnitude { get; } = effectMagnitude;

    /// <summary>The CSS class that animates the surface decoration (see AnimationCssGenerator).</summary>
    public string AnimationClass => "liquid_" + SpriteName;
}
