# Keep in sync with Dockerfile. Identical build - the only difference is the paired
# Dockerfile.graphics.dockerignore, which (unlike .dockerignore) does not exclude
# wwwroot/img/uf_*, so a local build on a machine with the licensed tileset bundles it into the
# image. Local-build-only: never run this in CI, and never push the resulting image to a public
# registry (see CLAUDE.md).
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .
RUN dotnet publish BlazorRogue.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
USER $APP_UID
ENTRYPOINT ["dotnet", "BlazorRogue.dll"]
